server:
  port: 8083

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/minipay_user?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        enabled: false

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
