server:
  port: 8081

spring:
  application:
    name: order-service
#    这里配置的是云数据库配置，开发请改为本地数据库配置
  datasource:
    url: jdbc:mysql://8.137.58.214:3306/minipay_order?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: yilinfeng123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: nacos.linqin.space
        username: nacos
        password: nacos

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
