server:
  port: 8084

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://8.137.58.214:3306/minipay_product?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: yilinfeng123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        enabled: false

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
