spring:
  application:
    name: inventory-service
  config:
    import:
      - optional:file:.env[.properties]
      - nacos:redis.yml
      - nacos:${spring.application.name}.yml
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:nacos.linqin.space}
      namespace: ${NACOS_NAMESPACE:minipay}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:}
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}
        namespace: ${spring.cloud.nacos.namespace}
        username: ${spring.cloud.nacos.username}
        password: ${spring.cloud.nacos.password}
      config:
        server-addr: ${spring.cloud.nacos.server-addr}
        namespace: ${spring.cloud.nacos.namespace}
        username: ${spring.cloud.nacos.username}
        password: ${spring.cloud.nacos.password}
        file-extension: yml
