server:
  port: 8086

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:mysql://localhost:3306/minipay_inventory?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
